### ISSUE TITLE
There is a problem with Application Menu

### ISSUE THREAD

**Issue by guinuxbr** [bahamondev/hide-titles#2]
**First of all, congratulations for the script.**

I have a little problem in Application Menu when enable the script.
There is a kind of title bar in the sub-menus.
Here goes an image that illustrates the issue:
https://i.imgur.com/MBcuuyJ.png

When I disable the script, the Application Menu works as expected.

My setup:
Arch Linux
KDE Plasma: 5.18.3
KDE Frameworks: 5.68.0
Qt version: 5.14.1

**Comment by bahamondev** [comment]
Thanks for the report!
The problem here is that in the application menu, submenus seems to be window instances. 
I also notice the same problem in Yakuake (the script removes its decoration and looks odd).
For now, I fixed it by not removing the window decorations in this two applications.

I think the best solution is to add a configuration for the script letting the user ban applications (with some applications banned by default). Maybe in a future release.

The new version is also uploaded to the Kde Store.

**Comment by guinuxbr** [comment]
Thank you for the update.
The KDE Store version is missing the "metadata.desktop" and this is not allowing to install directly with the KDE GUI.

I've managed to install using the "hide-titles.kwinscript" file from the "Relesas" tab and importing the file

By the way, the problem is gone now!

**Comment by bahamondev** [comment]
I've just updated the kde store kwin script with the release one

**Comment by guinuxbr** [comment]
Cool! Thanks.

Out of mere curiosity, any chance of you to launch as an AUR () package?

**Comment by bahamondev** [comment]
Not in the short run.

**Comment by zer09** [comment]
@bahamondev This is also affects on apps that you can disable their title bar, like firefox or chrome.
If you disable their title bar then, if you try to un-maximized them the title bar will appear with something shadow around them.

Here is the sample screenshot.
![Screenshot_20200721_065720](https://user-images.githubusercontent.com/780780/87995058-09fa9d80-cb21-11ea-9bf2-16f8c97c07fa.png)

Thanks.
